# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170623_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dis_num',
            field=models.IntegerField(null=True),
        ),
    ]
