# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_source_freq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='freq',
        ),
        migrations.AddField(
            model_name='data',
            name='freq',
            field=models.IntegerField(default=0),
        ),
    ]
