# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170629_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
