# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20170630_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
