# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='project',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dis_num',
        ),
    ]
