# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20170630_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='boundary',
        ),
    ]
