# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_remove_user_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_boundary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_boundary',
            field=models.IntegerField(default=0),
        ),
    ]
