# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-01 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20170630_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_boundary',
        ),
    ]
