# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_engine', models.CharField(max_length=10)),
                ('trans_source_lang', models.CharField(max_length=2)),
                ('trans_output_lang', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TransResult')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
