# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 03:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170606_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='transresult',
            name='trans_source',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transresult',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 3, 46, 51, 545231, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='voteresult',
            name='vote_result',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voteresult',
            name='vote_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 3, 46, 51, 546426, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transresult',
            name='trans_engine',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transresult',
            name='trans_output_lang',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transresult',
            name='trans_source_lang',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='voteresult',
            name='vote_result_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.TransResult'),
        ),
        migrations.AddField(
            model_name='transresult',
            name='trans_output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.TransList'),
        ),
    ]
