# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 05:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170607_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transresult',
            name='trans_output',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transresult',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='voteresult',
            name='vote_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='TransList',
        ),
    ]
