# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170607_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='transresult',
            name='trans_field',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
