# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_singleresult_single_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transresult',
            name='trans_output',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='SingleResult',
        ),
    ]
