# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170607_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transresult',
            name='trans_field',
        ),
    ]
