# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 02:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0011_remove_transresult_trans_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteresult',
            name='vote_result_id',
        ),
        migrations.AddField(
            model_name='transresult',
            name='vote_result',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transresult',
            name='vote_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='VoteResult',
        ),
    ]
