# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0012_auto_20170608_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transresult',
            name='vote_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
