# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0013_auto_20170609_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transresult',
            name='vote_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
