# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0015_transresult_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transresult',
            name='comment',
        ),
        migrations.AddField(
            model_name='transsource',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
