# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0016_auto_20170612_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('result',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.TransResult')),
            ],
        ),
        migrations.RemoveField(
            model_name='transsource',
            name='comment',
        ),
    ]
