# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0017_auto_20170613_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='transresult',
            name='score',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
