# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0018_transresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='transresult',
            name='user_trans',
            field=models.TextField(null=True),
        ),
    ]
