# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0019_transresult_user_trans'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_content', models.TextField(null=True)),
                ('trans_time', models.DateTimeField(blank=True, null=True)),
                ('vote_result', models.IntegerField(default=0)),
                ('vote_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=20, null=True)),
                ('user_trans', models.TextField(null=True)),
                ('trans_his',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.TransHistory')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='result',
        ),
        migrations.RemoveField(
            model_name='transresult',
            name='score',
        ),
        migrations.RemoveField(
            model_name='transresult',
            name='trans_output',
        ),
        migrations.RemoveField(
            model_name='transresult',
            name='trans_output_lang',
        ),
        migrations.RemoveField(
            model_name='transresult',
            name='trans_time',
        ),
        migrations.RemoveField(
            model_name='transresult',
            name='user_trans',
        ),
        migrations.RemoveField(
            model_name='transresult',
            name='vote_result',
        ),
        migrations.RemoveField(
            model_name='transresult',
            name='vote_time',
        ),
        migrations.AddField(
            model_name='transsource',
            name='trans_output_lang',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='transhistory',
            name='trans_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.TransResult'),
        ),
        migrations.AddField(
            model_name='comment',
            name='trans_his',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.TransHistory'),
        ),
    ]
