# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0023_auto_20170616_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transsource',
            name='trans_source_type',
        ),
    ]
